# Generated by Django 5.1.2 on 2024-10-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectData",
            fields=[
                ("proj_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(default="", max_length=255)),
                ("projtitle", models.CharField(default="", max_length=255)),
                ("proj_details", models.CharField(default="", max_length=10000)),
                ("pub_date", models.DateField()),
                ("pub_time", models.CharField(default="", max_length=20)),
                ("status", models.CharField(default="new", max_length=100)),
                ("proj_req_list", models.CharField(default="[]", max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name="RequestData",
            fields=[
                ("req_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(default="", max_length=255)),
                ("reqtitle", models.CharField(default="", max_length=255)),
                ("req_details", models.CharField(default="", max_length=5000)),
                ("pub_date", models.DateField()),
                ("pub_time", models.CharField(default="", max_length=20)),
                ("status", models.CharField(default="new", max_length=100)),
                ("proj_id", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="UserData",
            fields=[
                ("u_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(default="", max_length=255)),
                ("pub_date", models.DateField()),
                ("pub_time", models.CharField(default="", max_length=20)),
                ("role", models.CharField(default="new", max_length=100)),
            ],
        ),
    ]
